"""cria tabelas iniciais (channels, content_pieces, content_versions, approvals, publications)

Revision ID: e889fe32c3ac
Revises: 
Create Date: 2026-09-20 21:58:37.567398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e889fe32c3ac'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channels',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('content_pieces',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('channel_id', sa.UUID(), nullable=False),
    sa.Column('tema', sa.String(length=200), nullable=False),
    sa.Column('status', sa.Enum('PLANEJAMENTO', 'PESQUISA', 'ROTEIRIZACAO', 'PRODUCAO', 'EDICAO', 'REVISAO', 'AGUARDANDO_APROVACAO', 'APROVADO', 'AGUARDANDO_PUBLICACAO', 'PUBLICADO', 'REJEITADO', 'CANCELADO', 'COM_ERRO', name='statusconteudo'), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('content_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('content_piece_id', sa.UUID(), nullable=False),
    sa.Column('numero_versao', sa.Integer(), nullable=False),
    sa.Column('roteiro', sa.Text(), nullable=True),
    sa.Column('caminho_video', sa.String(length=500), nullable=True),
    sa.Column('caminho_thumbnail', sa.String(length=500), nullable=True),
    sa.Column('titulo_sugerido', sa.String(length=200), nullable=True),
    sa.Column('descricao_sugerida', sa.Text(), nullable=True),
    sa.Column('hashtags', sa.String(length=500), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['content_piece_id'], ['content_pieces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('approvals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('content_version_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDENTE', 'APROVADO', 'REJEITADO', 'ALTERACAO_SOLICITADA', 'CANCELADO', name='statusaprovacao'), nullable=False),
    sa.Column('plataformas_confirmadas', sa.String(length=200), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('respondido_em', sa.DateTime(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['content_version_id'], ['content_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('publications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('content_version_id', sa.UUID(), nullable=False),
    sa.Column('plataforma', sa.String(length=30), nullable=False),
    sa.Column('status', sa.Enum('PENDENTE', 'PUBLICADO', 'ERRO', name='statuspublicacao'), nullable=False),
    sa.Column('url_publicada', sa.String(length=500), nullable=True),
    sa.Column('erro_mensagem', sa.Text(), nullable=True),
    sa.Column('publicado_em', sa.DateTime(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['content_version_id'], ['content_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('publications')
    op.drop_table('approvals')
    op.drop_table('content_versions')
    op.drop_table('content_pieces')
    op.drop_table('channels')
    # ### end Alembic commands ###
